
summary = true
wrap = true
reverse = false
help_line = false
default_job = "check"

# Exporting "locations" lets you use them in an external
# tool, for example as a list of jump locations in an IDE
# or in a language server.
#
# See https://dystroy.org/bacon/config/#export-locations
#
# Set 'enabled' to true to have bacon always export locations
# This is equivalent to always adding -e to bacon commands
# but can still be canceled on specific launches with -E
#
# Possible line_format parts:
#  - kind: warning|error|test 
#  - path: complete absolute path to the file
#  - line: 1-based line number
#  - column: 1-based column
#  - message: description of the item
#  - context: unstyled lines of output, separated with escaped newlines (`\\n`)
[export] # startup bacon_ls
enabled = true
path = ".bacon-locations"
line_format = "{kind}:{path}:{line}:{column}:{message}"


[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = true

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--color", "always"]
need_stdout = true

[keybindings]
# internals
esc = "back"
q = "quit"

"?" = "help"

g = "scroll-to-top"
shift-g = "scroll-to-bottom"
j = "scroll-lines(1)"
d = "scroll-lines(8)"
k = "scroll-lines(-1)"
u = "scroll-lines(-8)"

s = "toggle-summary"
w = "toggle-wrap"
b = "toggle-backtrace"
shift-r = "refresh"

# job
t = "job:test"
r = "job:run"
c = "job:check"
shift-c = "job:check-all"
