# 将某些会话加入黑名单
blacklist = ["scratch"]

[default_session]
preview_command = "bkt --stale 30s -- eza -TF -L2 --follow-symlinks --icons --color=always {}"

[[session]]
name = "config"
path = "~/.config"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "echo $XDG_CONFIG_HOME"
