# 将某些会话加入黑名单
blacklist = ["scratch"]

[default_session]
preview_command = "bkt --stale 30s -- eza -TF -L2 --follow-symlinks --icons --color=always {}"

[[session]]
name = "tmux-config"
path = "~/.config/tmux"
startup_command = "nvim"

[[session]]
name = "nvim-config"
path = "~/.config/nvim"
startup_command = "nvim"
