#!/usr/bin/env zsh

setopt EXTENDED_GLOB

[[ -r "$_per_directory_history_directory" ]] && {
    local prefix result pattern
    
    prefix="${1//(#m)[\\*?[\]<>()|^~#]/\\$MATCH}"
    pattern="($prefix*)~($prefix)"
    
    [[ ${(t)ZSH_AUTOSUGGEST_HISTORY_IGNORE} == array ]] && {
        pattern="${pattern/\)(#e)/|${(j:|:)ZSH_AUTOSUGGEST_HISTORY_IGNORE})}"
    } 
    [[ ${(t)ZSH_AUTOSUGGEST_HISTORY_IGNORE} == scalar ]] && {
        pattern="${pattern/\)(#e)/|${ZSH_AUTOSUGGEST_HISTORY_IGNORE})}"
    } 

    result=${${(f)"$(tail -n 300 $_per_directory_history_directory | cut -d ';' -f2-)"}[(fR)$pattern]}

    [[ -n $result ]] && typeset -g suggestion=$result
}
