# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

syntax = "LuaJIT"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
call_parentheses = "Input"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
