#!/usr/bin/env zsh

local zopts fopts results=() result

zparseopts -E -D -F -A zopts -- p d || {
    print_msg error "flags is error"
    return 1
}

# 1 list sources
if (($+zopts[-p])); then
    result=${PWD:h}
    until [[ $result == / || $result == /home || $result == $HOME ]]; do
        results+=$result/
        result=${result:h}
    done
elif (($+zopts[-d])); then
    results=( ${(f)"$( dirs -pl | sed -n '1!p' | sed -e '/^\/$/d' -e '/^\/home$/d' -e '/^'${HOME//\//\\\/}'$/d' -e 's/$/\//' )"} )
else
    builtin cd "$@"
    return 0
fi

# 2 filter

fopts="
$FZF_DEFAULT_OPTS
+m -0
--prompt 'Cd> '
--delimiter / --nth '-1'
"

if (($#)); then
    results=$(eval 'print -l -- ${(M)results:#'"${${@[1]:#/*}:+*}${(j:*:)@}${${@[-1]:#*/}:+*}}")
else
    results=$(print -l -- $results | lscolors | FZF_DEFAULT_OPTS="$fopts" startup_fzf --popup)
fi

results=( ${(f)results} )

# 3 handle

if (($#results == 0)); then
    print_msg warn "$@ is not match|select any path"
    result=
elif (($#results == 1)); then
    result=$results
else
    select result in ${results:0:3}; do break; done
fi

[[ -n $result ]] && builtin cd $result
